# Generated by Django 4.1.9 on 2023-09-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuserprofile',
            name='user_groups',
            field=models.ManyToManyField(blank=True, null=True, to='auth.group'),
        ),
    ]
