# Generated by Django 4.1.9 on 2023-09-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_myuserprofile_user_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuserprofile',
            name='user_groups',
        ),
    ]
