# Generated by Django 4.1.9 on 2023-09-05 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('microblogs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='microblogpost',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_posts', to='users.myuserprofile'),
        ),
        migrations.AddField(
            model_name='microblogpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='users.myuserprofile'),
        ),
        migrations.AddField(
            model_name='microblogpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.myuserprofile'),
        ),
    ]
